// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.3
// source: pb/wsetserver.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Set方法请求数据格式
type WeightConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service   string  `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`     // 服务名
	Weigtht   *Matrix `protobuf:"bytes,2,opt,name=weigtht,proto3" json:"weigtht,omitempty"`     // 权重
	Namespace string  `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"` // 命名空间
}

func (x *WeightConfig) Reset() {
	*x = WeightConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wsetserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeightConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightConfig) ProtoMessage() {}

func (x *WeightConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wsetserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightConfig.ProtoReflect.Descriptor instead.
func (*WeightConfig) Descriptor() ([]byte, []int) {
	return file_pb_wsetserver_proto_rawDescGZIP(), []int{0}
}

func (x *WeightConfig) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WeightConfig) GetWeigtht() *Matrix {
	if x != nil {
		return x.Weigtht
	}
	return nil
}

func (x *WeightConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wsetserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wsetserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_pb_wsetserver_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Matrix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *Matrix) Reset() {
	*x = Matrix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wsetserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix) ProtoMessage() {}

func (x *Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wsetserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix.ProtoReflect.Descriptor instead.
func (*Matrix) Descriptor() ([]byte, []int) {
	return file_pb_wsetserver_proto_rawDescGZIP(), []int{2}
}

func (x *Matrix) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_pb_wsetserver_proto protoreflect.FileDescriptor

var file_pb_wsetserver_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x77, 0x73, 0x65, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0c, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x24, 0x0a, 0x07, 0x77, 0x65, 0x69, 0x67, 0x74, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x07, 0x77,
	0x65, 0x69, 0x67, 0x74, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x22, 0x1d, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x06, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x12, 0x1b, 0x0a,
	0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x32, 0x45, 0x0a, 0x10, 0x57, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31,
	0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_wsetserver_proto_rawDescOnce sync.Once
	file_pb_wsetserver_proto_rawDescData = file_pb_wsetserver_proto_rawDesc
)

func file_pb_wsetserver_proto_rawDescGZIP() []byte {
	file_pb_wsetserver_proto_rawDescOnce.Do(func() {
		file_pb_wsetserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_wsetserver_proto_rawDescData)
	})
	return file_pb_wsetserver_proto_rawDescData
}

var file_pb_wsetserver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_wsetserver_proto_goTypes = []interface{}{
	(*WeightConfig)(nil),  // 0: pb.WeightConfig
	(*Row)(nil),           // 1: pb.Row
	(*Matrix)(nil),        // 2: pb.Matrix
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_pb_wsetserver_proto_depIdxs = []int32{
	2, // 0: pb.WeightConfig.weigtht:type_name -> pb.Matrix
	1, // 1: pb.Matrix.rows:type_name -> pb.Row
	0, // 2: pb.WeightSetService.Set:input_type -> pb.WeightConfig
	3, // 3: pb.WeightSetService.Set:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_wsetserver_proto_init() }
func file_pb_wsetserver_proto_init() {
	if File_pb_wsetserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_wsetserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeightConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wsetserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wsetserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Matrix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_wsetserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_wsetserver_proto_goTypes,
		DependencyIndexes: file_pb_wsetserver_proto_depIdxs,
		MessageInfos:      file_pb_wsetserver_proto_msgTypes,
	}.Build()
	File_pb_wsetserver_proto = out.File
	file_pb_wsetserver_proto_rawDesc = nil
	file_pb_wsetserver_proto_goTypes = nil
	file_pb_wsetserver_proto_depIdxs = nil
}
