// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeightSetServiceClient is the client API for WeightSetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeightSetServiceClient interface {
	Set(ctx context.Context, in *WeightConfig, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type weightSetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeightSetServiceClient(cc grpc.ClientConnInterface) WeightSetServiceClient {
	return &weightSetServiceClient{cc}
}

func (c *weightSetServiceClient) Set(ctx context.Context, in *WeightConfig, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/pb.WeightSetService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeightSetServiceServer is the server API for WeightSetService service.
// All implementations must embed UnimplementedWeightSetServiceServer
// for forward compatibility
type WeightSetServiceServer interface {
	Set(context.Context, *WeightConfig) (*emptypb.Empty, error)
	mustEmbedUnimplementedWeightSetServiceServer()
}

// UnimplementedWeightSetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeightSetServiceServer struct {
}

func (UnimplementedWeightSetServiceServer) Set(context.Context, *WeightConfig) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedWeightSetServiceServer) mustEmbedUnimplementedWeightSetServiceServer() {}

// UnsafeWeightSetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeightSetServiceServer will
// result in compilation errors.
type UnsafeWeightSetServiceServer interface {
	mustEmbedUnimplementedWeightSetServiceServer()
}

func RegisterWeightSetServiceServer(s grpc.ServiceRegistrar, srv WeightSetServiceServer) {
	s.RegisterService(&WeightSetService_ServiceDesc, srv)
}

func _WeightSetService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeightConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightSetServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WeightSetService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightSetServiceServer).Set(ctx, req.(*WeightConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// WeightSetService_ServiceDesc is the grpc.ServiceDesc for WeightSetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeightSetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WeightSetService",
	HandlerType: (*WeightSetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _WeightSetService_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/wsetserver.proto",
}
